### PR TITLE
Python challenge -> Python track

### PR DESCRIPTION
**Pull request by colinmorris**
Sorry, this is still a bit disorganized, but the changes to the notebooks themselves are complete. (I just need to tidy up/document the workflow around "rendering" them, uploading them with the API, etc.)

The first commit in this branch has the original Python challenge notebooks as they looked when I downloaded them from kaggle. So probably the best way to see the notebook changes is to diff against that commit (I created a lightweight tag for it, `orignbs`, so you can do something like `git diff orignbs nb-tools notebooks/partials/`).

To see what the notebooks look like when the macros get expanded out, you can run `publish.sh partials/python/*.ipynb` (you may need to `pip install python-box` first). They'll get written to `rendered/`.

### CODE REVIEW

**Comment by dansbecker** [comment]
I assume your aware that the URLs between notebooks still need to get updated?

**Comment by dansbecker** [comment]
I prefer having a header at the top of a page saying what the topic is (as you see in https://www.kaggle.com/colinmorris/learn-python-challenge-day-3 ) rather than jumping straight into some text, like

_Python has a type `bool` which can take on one of two values: `True` and `False`._ as the page does now. The header helps feel like I've got some context when reading, rather than worrying I've come into an explanation midstream.

**Comment by dansbecker** [comment]
As a convention, we should use the header `Keep Going` above the last line in an exercises:

When you're ready to continue, [click here](https://www.kaggle.com/colinmorris/foo-bar-tut-4) to continue on to the next tutorial on lists and tuples.

**Comment by dansbecker** [comment]
Aside from other items listed here, LGTM

**Comment by colinmorris** [comment]
re urls: Yeah, I haven't actually created the new kernels yet.

re headers: SGTM. At one point I was worried they would look redundant if they repeated the title of the notebook, but it looks like lots of Learn NBs do this. Would you also have headings for the exercises? And if so, any opinions on the format? Something like: "# Exercise: Lists and tuples"?

**Comment by dansbecker** [comment]
Currently most exercises use `Intro` or `Introduction` for the first header.  

I think we should stick with that.

**Pull request merged**
